### ISSUE TITLE
Mosquitto jwt

### ISSUE THREAD

**Issue by andriwarda** [cyrilcc/mosquitto_auth_plugin_jwt#2]
Hello,
I want to ask you about this plugin. This plugin is same with mosquitto plugin jwt from https://github.com/jpmens/mosquitto-auth-plug ?

**Comment by cyrilcc** [comment]
Hello,

  Thank you for sharing.  This project is probably more advanced than mine.
  I did this implementation a long time ago for experimentation purpose because I didn't find any other.
